const sidebarData = require("./config/sidebar/index.json");
const docusaurusData = require("./config/docusaurus/index.json");

const getDocId = (doc) => {
  return doc
    .replace(/\.mdx?$/, "")
    .split("/")
    .slice(1)
    .join("/");
};

const getItem = (item) => {
  const type = item._template;

  const itemProps = {
    type: type,
  };

  if (type === "doc") {
    if (!item.document) {
      return [];
    }

    itemProps.id = getDocId(item.document);

    if (item.label) {
      itemProps.label = item.label;
    }
  }

  if (type === "category") {
    if (item.title) {
      itemProps.label = item.title;
    }

    if (item.link && item.link !== "none") {
      if (item.link === "doc" && item.docLink) {
        itemProps.link = {
          type: "doc",
          id: getDocId(item.docLink),
        };
      } else if (item.link === "generated") {
        itemProps.link = {
          type: "generated-index",
        };
      } else {
        return [];
      }
    }

    itemProps.items = item.items.flatMap((item) => {
      return getItem(item);
    });
  }

  if (type === "link") {
    if (item.href && item.title) {
      itemProps.label = item.title;
      itemProps.href = item.href;
    } else {
      return [];
    }
  }

  return [itemProps];
};

const sidebars = {
  docSidebar: sidebarData.items.flatMap((item) => {
    return getItem(item);
  }),

  wikiSidebar: [
    {
      type: "autogenerated",
      dirName: "wiki",
    },
  ],

  openApiSidebar: docusaurusData.openApiSidebar || [],

  // graphQlSidebar: [
  //   { type: "doc", id: "api/queries" },
  //   { type: "doc", id: "api/mutations" },
  //   { type: "doc", id: "api/objects" },
  //   { type: "doc", id: "api/interfaces" },
  //   { type: "doc", id: "api/enums" },
  //   { type: "doc", id: "api/unions" },
  //   { type: "doc", id: "api/inputObjects" },
  //   { type: "doc", id: "api/scalars" },
  // ],
};

module.exports = sidebars;