name: Notify by Slack on Review tag

on:
  push:
    branches:
      - main

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find changed markdown files
        id: changed_files
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            # First commit, diff against empty tree
            git diff --name-only ${{ github.sha }} | grep '\.mdx\?$' > changed_files.txt || true
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.mdx\?$' > changed_files.txt || true
          fi

      - name: Check for review tag
        id: review_check
        run: |
          found=false
          files_with_review=""
          while read file; do
            if grep -q 'review: true' "$file"; then
              found=true
              files_with_review="$files_with_review $file"
              echo "File $file has review: true"
            fi
          done < changed_files.txt
          echo "found=$found" >> $GITHUB_OUTPUT
          echo "files=$files_with_review" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        if: steps.review_check.outputs.found == 'true'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "The following markdown files with `review: true` were committed to main: ${{ steps.review_check.outputs.files }}. Please review!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
