name: Notify by Teams on Translate tag

on:
  push:
    branches:
      - main

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find changed markdown files
        id: changed_files
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            # First commit, diff against empty tree
            git diff --name-only ${{ github.sha }} | grep '\.mdx\?$' > changed_files.txt || true
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.mdx\?$' > changed_files.txt || true
          fi

      - name: Check for translate tag
        id: translate_check
        run: |
          found=false
          while read file; do
            if grep -q 'translate: true' "$file"; then
              found=true
              echo "File $file has translate: true"
            fi
          done < changed_files.txt
          echo "found=$found" >> $GITHUB_OUTPUT

      - name: Send MS Teams notification
        if: steps.translate_check.outputs.found == 'true'
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "The following markdown files with `translate: true` were committed to main: ${{ steps.translate_check.outputs.files }}. Please translate!"
          notification-color: 17a2b8
          timezone: Europe/Paris
          verbose-logging: true
