name: Notify by Teams on Translate tag

on:
  push:
    branches:
      - main

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find changed markdown files
        id: changed_files
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            # First commit, diff against empty tree
            git diff --name-only ${{ github.sha }} | grep '\.mdx\?$' > changed_files.txt || true
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.mdx\?$' > changed_files.txt || true
          fi

      - name: Check for translate tag
        id: translate_check
        run: |
          found=false
          files_with_translate=""
          while read file; do
            if grep -q 'translate: true' "$file"; then
              found=true
              files_with_translate="$files_with_translate $file"
              echo "File $file has translate: true"
            fi
          done < changed_files.txt
          echo "found=$found" >> $GITHUB_OUTPUT
          echo "files=$files_with_translate" >> $GITHUB_OUTPUT

      - name: Send MS Teams notification
        if: steps.translate_check.outputs.found == 'true'
        run: | 
          curl --ssl-no-revoke -X POST \
          --location ${{ secrets.MS_TEAMS_HTTP_POST_URL }} \
          --header 'Content-Type: application/json' \
          --data '{ \
            "type": "message", \
            "attachments": [{ \
              "contentType": "application/vnd.microsoft.card.adaptive", \
              "content": { \
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json", \
                "type": "AdaptiveCard", \
                "version": "1.3", \
                "body": [ { \
                  "type": "TextBlock", \
                  "text": "The following markdown files with `translate: true` were committed to main: ${{ steps.review_check.outputs.files }}. Please review!", \
                  "wrap": true }]}}]}'
