name: Test notifications

on:
  workflow_dispatch:

jobs:
  test-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack test notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "Test notification from GitHub Actions (Slack)"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Email test notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Test notification from GitHub Actions (Email)"
          to: ${{ secrets.NOTIFY_EMAIL_TO }}
          from: ${{ secrets.NOTIFY_EMAIL_FROM }}
          body: |
            This is a test notification from GitHub Actions (Email).

      - name: Send Teams test notification
        run: | 
          curl --ssl-no-revoke -X POST \
          --location ${{ secrets.MS_TEAMS_HTTP_POST_URL }} \
          --header 'Content-Type: application/json' \
          --data '{ \
            "type": "message", \
            "attachments": [{ \
              "contentType": "application/vnd.microsoft.card.adaptive", \
              "content": { \
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json", \
                "type": "AdaptiveCard", \
                "version": "1.3", \
                "body": [ { \
                  "type": "TextBlock", \
                  "text": "This is a test notification from GitHub Actions (Teams).", \
                  "wrap": true }]}}]}'
